//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABT.Test.TestPlans.Diagnostics.TestOperations.SCPI_VISA_Instruments {
    using ABT.Test.TestLib;
    using ABT.Test.TestLib.TestConfiguration;
    using System;
    using System.Diagnostics;
    using static ABT.Test.TestLib.TestConfiguration.Assertions;
    
    
    internal class TestMethods {
        
        internal static string MSMU_34980A() {
			if (TestLib.testSequence.IsOperation) Debug.Assert(TestOperation(NamespaceTrunk: "SCPI_VISA_Instruments", Description: "Diagnostics, SCPI VISA Instruments.", TestGroups: "TestMethods|MoreMethods"));
			Debug.Assert(TestGroupPrior(Class: "NONE"));
			Debug.Assert(TestGroup(Class: "TestMethods", Description: "Diagnostics.", CancelNotPassed: "false", Independent: "true", Methods: "MSMU_34980A|MM_34401A|MSO_3014|PS_E3634A|PS_E3649A"));
			if (TestLib.testSequence.IsOperation) Debug.Assert(TestGroupNext(Class: "MoreMethods"));
			Debug.Assert(MethodPrior(Name : "NONE"));
			Debug.Assert(MethodCustom(Name: "MSMU_34980A", Description: "Keysight 34980A Multifunction Switch/Measurement Units.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MM_34401A"));

            TestIndices.Method.Log.AppendLine(nameof(MSMU_34980A));
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MM_34401A() {
			Debug.Assert(MethodPrior(Name: "MSMU_34980A"));
			Debug.Assert(MethodCustom(Name: "MM_34401A", Description: "Keysight 34401A Digital Multi-Meters.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MSO_3014"));

            TestIndices.Method.Log.AppendLine(nameof(MM_34401A));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MSO_3014() {
			Debug.Assert(MethodPrior(Name: "MM_34401A"));
			Debug.Assert(MethodCustom(Name: "MSO_3014", Description: "Tektronix MSO-3014 Mixed-Signal Oscilloscopes.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "PS_E3634A"));

            TestIndices.Method.Log.AppendLine(nameof(MSO_3014));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string PS_E3634A() {
			Debug.Assert(MethodPrior(Name: "MSO_3014"));
			Debug.Assert(MethodCustom(Name: "PS_E3634A", Description: "Keysight E3634A Power Supplies.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "PS_E3649A"));

            TestIndices.Method.Log.AppendLine(nameof(PS_E3634A));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string PS_E3649A() {
			Debug.Assert(MethodPrior(Name: "PS_E3634A"));
			Debug.Assert(MethodCustom(Name: "PS_E3649A", Description: "Keysight E3649A Power Supplies.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "NONE"));

            TestIndices.Method.Log.AppendLine(nameof(PS_E3649A));         
            return nameof(EVENTS.UNSET);
        }
    }
    
    internal class MoreMethods {
        
        internal static string MoreMSMU_34980A() {
            if (TestLib.testSequence.IsOperation) Debug.Assert(TestGroupPrior(Class: "TestMethods"));
			Debug.Assert(TestGroup(Class: "MoreMethods", Description: "Diagnostics.", CancelNotPassed: "false", Independent: "true", Methods: "MoreMSMU_34980A|MoreMM_34401A|MoreMSO_3014|MorePS_E3634A|MorePS_E3649A"));
			Debug.Assert(TestGroupNext(Class: "NONE"));
			Debug.Assert( MethodPrior ( Name :  "NONE"));
			Debug.Assert(MethodCustom(Name: "MoreMSMU_34980A", Description: "Keysight 34980A Multifunction Switch/Measurement Units.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MoreMM_34401A"));

            TestIndices.Method.Log.AppendLine(nameof(MoreMSMU_34980A));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MoreMM_34401A() {
			Debug.Assert(MethodPrior(Name: "MoreMSMU_34980A"));
			Debug.Assert(MethodCustom(Name: "MoreMM_34401A", Description: "Keysight 34401A Digital Multi-Meters.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MoreMSO_3014"));

            TestIndices.Method.Log.AppendLine(nameof(MoreMM_34401A));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MoreMSO_3014() {
			Debug.Assert(MethodPrior(Name: "MoreMM_34401A"));
			Debug.Assert(MethodCustom(Name: "MoreMSO_3014", Description: "Tektronix MSO-3014 Mixed-Signal Oscilloscopes.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MorePS_E3634A"));

            TestIndices.Method.Log.AppendLine(nameof(MoreMSO_3014));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MorePS_E3634A() {
			Debug.Assert(MethodPrior(Name: "MoreMSO_3014"));
			Debug.Assert(MethodCustom(Name: "MorePS_E3634A", Description: "Keysight E3634A Power Supplies.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "MorePS_E3649A"));

            TestIndices.Method.Log.AppendLine(nameof(MorePS_E3634A));         
            return nameof(EVENTS.UNSET);
        }
        
        internal static string MorePS_E3649A() {
			Debug.Assert(MethodPrior(Name: "MorePS_E3634A"));
			Debug.Assert(MethodCustom(Name: "MorePS_E3649A", Description: "Keysight E3649A Power Supplies.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "NONE"));

            TestIndices.Method.Log.AppendLine(nameof(MorePS_E3649A));         
            return nameof(EVENTS.UNSET);
        }
    }
}
namespace ABT.Test.TestPlans.Diagnostics.TestOperations.Miscellaneous {
    using ABT.Test.TestLib;
    using ABT.Test.TestLib.TestConfiguration;
    using System;
    using System.Diagnostics;
    using static ABT.Test.TestLib.TestConfiguration.Assertions;
    
    
    internal class USB_ERB24 {
        
        internal static string USB_ERB24_SelfTest() {
			Debug.Assert(TestOperation(NamespaceTrunk: "Miscellaneous", Description: "Miscellaneous items, including instruments that aren\'t both SCPI & VISA instruments.", TestGroups: "USB_ERB24"));
			if (TestLib.testSequence.IsOperation) Debug.Assert(TestGroupPrior(Class: "NONE"));
			Debug.Assert(TestGroup(Class: "USB_ERB24", Description: "USB_ERB24 Relays.", CancelNotPassed: "false", Independent: "true", Methods: "USB_ERB24_SelfTest"));
			if (TestLib.testSequence.IsOperation) Debug.Assert(TestGroupNext(Class: "NONE"));
			Debug.Assert( MethodPrior ( Name :  "NONE"));
			Debug.Assert(MethodCustom(Name: "USB_ERB24_SelfTest", Description: "USB_ERB24 Diagnostics.", CancelNotPassed: "false"));
			Debug.Assert(MethodNext(Name: "NONE"));

            TestIndices.Method.Log.AppendLine(nameof(USB_ERB24_SelfTest));         
            return nameof(EVENTS.UNSET);
        }
    }
}
