//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABT.Test.TestPlans.Diagnostics.InstrumentsDrivers {
    using ABT.Test.TestLib.InstrumentDrivers.Generic;
    using ABT.Test.TestLib.InstrumentDrivers.Multifunction;
    using ABT.Test.TestLib.InstrumentDrivers.PowerSupplies;
    
    internal class ID {
        //internal static MSMU_34980A_SCPI_NET MSMU = ((MSMU_34980A_SCPI_NET)(TestLib.Data.InstrumentDrivers["MSMU1_34980A"]));
        //internal static PS_E3649A_SCPI_NET P12V_N12V = ((PS_E3649A_SCPI_NET)(TestLib.Data.InstrumentDrivers["PS1ε2_E3649A"]));
        //internal static PS_E3634A_SCPI_NET P28V = ((PS_E3634A_SCPI_NET)(TestLib.Data.InstrumentDrivers["PS3_E3634A"]));
        internal static SCPI_NET WG = ((SCPI_NET)(TestLib.Data.InstrumentDrivers["WG1_33120A"]));
    }
}
